apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: template-hub-registry-server
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: template-hub-registry-server
subjects:
- kind: ServiceAccount
  name: template-hub-registry-server-sa
