apiVersion: v1
kind: Service
metadata:
  name: template-hub-registry-server
spec:
  selector:
    app: template-hub-registry-server
  ports:
    - name: http
      port: 80
      targetPort: http
    - name: https
      port: 443
      targetPort: http
